### ISSUE TITLE
New player movement cordination in past game

### ISSUE THREAD

**Issue by raaaas** [RiotGames/developer-relations#110]
Hello,

I want to have Player moves in game, Since i got ban to run my script ! and they wont lift it i cannot extract it from Replay online ;) 

So please help to create path optimization for research

**Comment by Querijn** [comment]
boy

**Comment by Querijn** [comment]
no

**Comment by raaaas** [comment]
https://youtu.be/eHipy_j29Xw?t=136 

just in case if you just came out of the cave recently

**Comment by supergrecko** [comment]
Extracted from the League TOS [link)(https://na.leagueoflegends.com/en/legal/termsofuse#updates-modifications)

> ix. Using any unauthorized third party programs, including mods, hacks, cheats, scripts, bots, trainers and automation programs that interact with the Software in any way, for any purpose, including any unauthorized third party programs that intercept, emulate, or redirect any communication between the Software and Riot Games and any unauthorized third party programs that collect information about the Game by reading areas of memory used by the Software to store information;

**Comment by raaaas** [comment]
okey genuine you can read good, 

The move ment DATA stored in replay file client loads it and just like old gramaphon plays it 

ALL MOVE MENT DATA ARE STORED and ITS FREE TO Download and since  is not intellectual property  and its free to use, its free to extract DATA from. 

im just want short cut ;) other wise everything done and data set could generated like 1 week with my servers ;)

**Comment by Querijn** [comment]
There is none. Read the replay file.

**Comment by raaaas** [comment]
are you sure ?
![image](https://user-images.githubusercontent.com/7237781/56374525-a34d4c80-6218-11e9-9148-c1304905f9e9.png)

**Comment by Querijn** [comment]
That's a third party rest API that feeds the game encrypted information. It most likely 'copies and pastes' the spectator rest api data

**Comment by supergrecko** [comment]
I'm not sure if asking whether we can read or not is a great idea when your question is unclear. I initially thought you were looking to simulate player movement in-game.

**Comment by raaaas** [comment]
finally, im not looking for do anything in-gmae.

ALL i want to do is, find HEAT map, extract strategy to teach people

**Comment by Krissalyce** [comment]
This data is intentionally not available, because the abuse of this data could lead to tracking jungle routes and times for junglers, and exploited to give unfair advantages to malicious players. While it's possible that in the future, this data may be released with Riot Sign On, granular player movements in game are currently considered private data. Use the timeline api with the broad stroke data provided and interpolate.

**Comment by Querijn** [comment]
I had the same issue Grecko has, combining a paragraph of "player moves in game", "scripts" and "i got ban" is really confusing. Krissalyce is right on the mark on the current Riot stance on this data, it's not public or planned to be public.

**Comment by raaaas** [comment]
> 
> 
> I had the same issue Grecko has, combining a paragraph of "player moves in game", "scripts" and "i got ban" is really confusing. Krissalyce is right on the mark on the current Riot stance on this data, it's not public or planned to be public.

the reson i got bannd because i was lazy to write decodeing, so i just injecte hope for extracting the game replay. 

and as he said there is a another way for me : "Use the timeline api with the broad stroke data provided and interpolate."

**Comment by raaaas** [comment]
> This data is intentionally not available, because the abuse of this data could lead to tracking jungle routes and times for junglers, and exploited to give unfair advantages to malicious players. While it's possible that in the future, this data may be released with Riot Sign On, granular player movements in game are currently considered private data. Use the timeline api with the broad stroke data provided and interpolate.

So you mean Riot have the data and not publishing to public because some user could find better path by data and not watching online match ? or youtube like Tarzan which teach people best jungler pathing ? 
https://www.youtube.com/watch?v=KuRwf34wVmM

so if its unfair please ban n1 jungler in na ;) 


or you mean you are selling this data to top dollar so they could have advantage in game ?

**Comment by Krissalyce** [comment]
No, the data may or may not be recorded. It is unclear.

You misunderstand me. Tarzan is not exploiting anything because he is not using personalized jungler data to inform him of his enemy's path. He is using non-personalized experience to teach players to play the game. The difference between personalized and non-personalized data is key.

By using this theoretical position API, one could obtain personalized pathing data, which can be abused. This is why Riot has made the conscious decision to make this data considered private. This, and any other data that could be used to adversely affect the match to create non-normal gameplay, is privatized.

It is an unfortunate side effect that certain projects become non-viable, including my own, which intended to teach players about overextending and [dude potential](https://www.youtube.com/watch?v=v_qxqKjkuug). However, it is for the sanctity of the game and I agree with Riot's stance.

This is unlikely to change until Riot Sign On allows for secure access to ensure a summoner is who they claim to be, and even then it is a big if.

**Comment by RiotTuxedo** [comment]
Sorry everyone. I'm going to close this issue as it's more of a discussion than an issue or feature request. If it is a feature request, encrypting the game data is an intentional choice. If you'd like, you can move this discussion to the [Discord](https://discord.gg/riotapi).
