### ISSUE TITLE
Inflexible Batch Size in League/v4 API

### ISSUE THREAD

**Issue by PranayPant** [RiotGames/developer-relations#124]
Currently, you get a fixed size of 205 when hitting the endpoint `https://na1.api.riotgames.com/lol/league/v4/entries/RANKED_SOLO_5X5/{TIER}/{DIVISION}`

If need thousands of summoners, this can be very inefficient, as I will have to make multiple calls to the api.

Anyway to increase the batch size to higher limits?

**Comment by RiotTuxedo** [comment]
@PranayPant when the size of the page is fixed it makes it a lot easier to cache. When the size is dynamic the cache becomes less effective. We may look into adjusting the page size in the future, but for now we're happy with the number of results per page.

The efficiency is subjective. While having to make multiple calls on the client side may feel inefficient, it may be efficient for the service (as I mentioned because of caching). The service may become more inefficient if we adjust the entries per page or allow dynamic page sizes. Because the league service is the bottleneck, the goal is to make it as efficient as possible for the league service to provide the requested data at the cost of efficiency for the developer.
