### ISSUE TITLE
Match-v4 contains the original unencrypted account id in "matchHistoryUri"

### ISSUE THREAD

**Issue by Querijn** [RiotGames/developer-relations#13]
` "matchHistoryUri": "/v1/stats/player_history/EUW1/35084043"`

Might be considered an issue..

**Comment by xanerolozorus** [comment]
Following our small chat on Discord, the visible account ID within matchHistoryUri is also used on the public web pages of match history to highlight a specific player :  https://matchhistory.euw.leagueoflegends.com/en/#match-details/EUW1/2445019385/35084043?tab=overview

**Comment by molenzwiebel** [comment]
This is intentional according to Tux. There is no way to hide this, since this is a link that needs to work even when not associated with any api key.

**Comment by Colorfulstan** [comment]
So there is a new security layer preventing publication of user's account id, but all it is in the end is an obfuscation because you still can get it if you really want to...but you can't use the unencrypted uri.

Am I'm too nitpicky here or does this basically make the whole thing a big pile of ... ?

I guess it's gonna be a "feature" in the end, since this should allow to still build the public matchhistory url for a user, just with a bunch of (in light of this issue) unneccessary overhead

**Comment by Querijn** [comment]
But doesn't the match history api need to be updated to support v4? Or can they just completely opt-out of this feature?

**Comment by Colorfulstan** [comment]
I'm afraid it might result in removal of the sharable match history on the web in the end, which seems to be the only way to ensure the security layer isn't undermined

**Comment by molenzwiebel** [comment]
![image](https://user-images.githubusercontent.com/3594254/49290738-10e61f80-f4a8-11e8-92f1-b4b885c3badf.png)
![image](https://user-images.githubusercontent.com/3594254/49290747-180d2d80-f4a8-11e8-9f85-207e607885aa.png)

**Comment by riottuxedo** [comment]
This field provides a portion of a URI for a given player's match history. The value of this field would be invalid if it were to be encrypted. The URI for a player's match history may be updated in the future.
