### ISSUE TITLE
match-v4 getMatch missing perkSubStyle for some participants

### ISSUE THREAD

**Issue by thomasmarton** [RiotGames/developer-relations#139]
In very rare cases (and even then, only on some of the participants), the perkSubStyle field is not present in the response when in a game after runes reforged, all participants should have that field.

Developer impact: I'd say minor inconvenience cause it can be calculated based on the selected runes (which are present)
Player impact: None cause the client doesn't display the secondary tree, it only displays the runes picked from it. (but the ACS response doesn't have that field either)

According to metamilo#7850 on the discord, this happens once every 100k games and the only match he could provide for you to look at was 3073596764 on NA. In that game, the 3rd participant was missing the perkSubStyle field.

**Comment by joshuaolufs** [comment]
I (metamilo#7850) suspect it may have something to do with the default pages since the runes for that participant are identical to the ones for the default page named "Resolve: The Colossus". If this is true then it should show perkSubStyle = 8200.

From the response we get the following values for participant 3.
perk0: 8437
perk1: 8446
perk2: 8444
perk3: 8451
perk4: 8224
perk5: 8237

And from the communitydragon perkstyles.json located here https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/default/v1/perkstyles.json

"defaultPageName":"Resolve: The Colossus","defaultSubStyle":8200,"defaultPerks":[8437,8446,8444,8451,8224,8237,5008,5002,5001]

**Comment by tisbells** [comment]
Closing out old issues. Match-v4 is no longer supported. Feel free to reopen/comment if you feel this is in error.
