### ISSUE TITLE
[BUG] Matchlist endpoint does not return some matches for some users

### ISSUE THREAD

**Issue by trebonius0** [RiotGames/developer-relations#147]
For user EUNE - AlF2ih45 , the matchlist endpoint does not return the last 4 matches from this user (gameIds: 2237722389, 2237694291, 2220461978, 2237691660)

**Player Impact**
The player will see an incomplete list of matches on his profile  on a lot of websites

Edit: Here is a log with a lot more of users impacted (alongside the gameIds not appearing in their matchlist at the time of the request) [incomplete.log](https://github.com/RiotGames/developer-relations/files/3468107/incomplete.log) (timestamps are GMT+2)
Edit2: updated incomplete.log file

**Comment by cohenu** [comment]
it seems like matchlist endpoint is missing a lot of data.

please look on that user for example Itamarb in EUW, I got only 30 games in response from Riot with no solo/duo games at all while in op.gg you you can see that he have almost 400 games in ranked
https://euw.op.gg/summoner/userName=itamarb

**Comment by RiotTuxedo** [comment]
@trebonius0 @cohenu This is an issue we're aware of that's related to how matches got associated with player accounts. They're working on reverting the change that created this issue. Once this change is reverted there will be a gap in match history for these players from 8/1 through the date when the revert is deployed. Matches before 7/31 will show up after the change is reverted. This should only affect a small subset of players and the long term goal is to find and resolve the issues with matches played in this window, but it'll likely happen as part of a migration rather than a one-off to solve this issue specifically.

**Comment by tisbells** [comment]
Closing out old issues. Match-v4 is no longer supported. Feel free to reopen/comment if you feel this is in error.
