### ISSUE TITLE
[BUG]LeagueV4 API response a void JSON

### ISSUE THREAD

**Issue by xbacon14** [RiotGames/developer-relations#219]
I´m using the RIOT API to develop a simple web app and the API response a void JSON

**Comment by sousa-andre** [comment]
The League-API returns an array of objects containing user rank related data for the different types of matches (e.g. Solo/Duo, Flex, ..) if such exists. Since summoner you checked returned an empty list, the player have no ranked data to be shown. 
Note that you can only retrieve the current season rank data with League-API!

**Comment by xbacon14** [comment]
Thanks, i forgot that the seanon was over Enviado do Email para Windows 10 De: André SousaEnviado:viernes, 10 de enero de 2020 12:19Para: RiotGames/developer-relationsCc:Italo Golin; AuthorAssunto: Re: [RiotGames/developer-relations] [BUG]LeagueV4 API response a void JSON (#219) The League-API returns an array of objects containing user rank related data for the different types of matches (e.g. Solo/Duo, Flex, ..) if such exists. Since summoner you checked returned an empty list, the player have no ranked data to be shown.Note that you can only retrieve the current season rank data with League-API!—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by stelar7** [comment]
Feel free to close the issue if its solved :)
