### ISSUE TITLE
Missing PlayerDTO in Match-V4 for Custom game only

### ISSUE THREAD

**Issue by g45t345rt** [RiotGames/developer-relations#257]
https://na1.api.riotgames.com/lol/match/v4/matches/3337167152

`    "participantIdentities": [
        {
            "participantId": 1
        },
        {
            "participantId": 2
        },
        {
            "participantId": 3
        },
        {
            "participantId": 4
        },
        {
            "participantId": 5
        },
        {
            "participantId": 6
        },
        {
            "participantId": 7
        },
        {
            "participantId": 8
        },
        {
            "participantId": 9
        },
        {
            "participantId": 10
        }
    ]`

**Comment by bangingheads** [comment]
This is due to the fact customs are considered private data. You can see the champions and manually map them to players on your own, or if on a larger scale you can use the tournament API.

A note from discord: 

Currently, custom game data (excluding the tournament system), is not retrievable from the API due to privacy policies.

A lot of these private things, like custom modes, champion mastery grade, etc that developers would like, are all things that one of the users in each game may not want to be publicly pull-able. Whereas, all users agree to it being pull-able in all other official games. While a normal game isn't try-hard like ranked, the user is still probably playing with the goal to win or compete in the game as intended. This may not always be the case in a custom mode.

The tournament system also takes into account a user's agreement, as the user is choosing to participate in an official game (the tournament system) and therefore giving some consent on data pulling for those specific games by using the tournament API.

The shining light to this, is that Riot is slowly but surely working towards an external RSO (Riot Sign-On) solution. Meaning, we as developers, can have users authenticate into Riot (officially) via the API. Which if all goes all, means a user could potentially give us their consent to go view their custom game data or champion mastery grades, etc.. but you would probably need consent per user to do these special calls, versus a blanket policy of letting developers go retrieve more private information.

**Comment by g45t345rt** [comment]
Oh that's why. I thought it was a bug.
Thanks for the fast response!

**Comment by RiotTuxedo** [comment]
Maybe I can add documentation to clarify this for future devs. Thanks for reporting this. Helpful feedback.

**Comment by RiotTuxedo** [comment]
The documentation has been updated to reflect the `PlayerDto` is excluded for custom games.
https://developer.riotgames.com/apis#match-v4/GET_getMatch
