### ISSUE TITLE
LeagueListDTO does not match returned JSON

### ISSUE THREAD

**Issue by stelar7** [RiotGames/developer-relations#29]
The fields `playerOrTeamId` and `playerOrTeamName` has been renamed in v4.
There might be some other changes too, but they are all undocumented, so i dont know.

**Comment by RiotTuxedo** [comment]
Do you have an endpoint and sample response where these fields aren't what you're expecting?

```
{
    "tier": "MASTER",
    "leagueId": "bb7f45c3-66d1-3b22-bc68-7a6c65b38c4e",
    "entries": [
        {
            "wins": 665,
            "losses": 636,
            "rank": "I",
            "playerOrTeamName": "Lycho",
            "playerOrTeamId": "44472302",
            "leaguePoints": 0
        }
    ]
}
```

**Comment by Derpthemeus** [comment]
https://na1.api.riotgames.com/lol/league/v4/positions/by-summoner/rtBoABIL8T_J690zXoVKNSJDTJ20K6Db5d59RjCXMudF9P4
```
[
    {
        "queueType": "RANKED_SOLO_5x5",
        "summonerName": "Derpthemeus",
        "wins": 35,
        "losses": 38,
        "rank": "IV",
        "leagueName": "Karma's Commandos",
        "leagueId": "926dd230-2340-11e8-bb3d-c81f66cf135e",
        "tier": "GOLD",
        "summonerId": "rtBoABIL8T_J690zXoVKNSJDTJ20K6Db5d59RjCXMudF9P4",
        "leaguePoints": 0
    },
    {
        "queueType": "RANKED_FLEX_SR",
        "summonerName": "Derpthemeus",
        "wins": 17,
        "losses": 17,
        "rank": "IV",
        "leagueName": "Veigar's Berserkers",
        "leagueId": "0e3a89e0-69b3-11e8-a566-c81f66dbb56c",
        "tier": "GOLD",
        "summonerId": "rtBoABIL8T_J690zXoVKNSJDTJ20K6Db5d59RjCXMudF9P4",
        "leaguePoints": 0
    }
]
```

**Comment by MingweiSamuel** [comment]
To clarify, it seems that LeagueItemDTO's documentation still contains the old "playerOrTeamName" and "playerOrTeamId" when in reality it is returning the new "summonerName" and "summonerId".

This affects the league endpoints: (since they use LeagueListDTO which uses LeagueItemDTO)
- /lol/league/v4/challengerleagues/by-queue/{queue}
- /lol/league/v4/grandmasterleagues/by-queue/{queue}
- /lol/league/v4/leagues/{leagueId}
- /lol/league/v4/masterleagues/by-queue/{queue}

Positions is not affected because it uses Set[LeaguePositionDTO] instead:
- /lol/league/v4/positions/by-summoner/{encryptedSummonerId}

**Comment by kargnas** [comment]
The attributes hotStreak, veteran, freshBlood, inactive should be available on v4 LeagueListDTO, but still I can't see these attributes.

**Comment by RiotTuxedo** [comment]
I've confirmed these missing fields are the result of a bug and they should return early this next week.

**Comment by gustavoja** [comment]
Hello, 
Looking at this conversation and the changes posted [here](https://www.riotgames.com/en/DevRel/positional-rankings-update)

I think you may need to update the LeaguePostionDTO [doc](https://developer.riotgames.com/api-methods/#league-v4/GET_getAllLeaguePositionsForSummoner) because you're still referencing the field  "playerOrTeamName  string" which has changed to summonerName.


<img width="674" alt="captura de pantalla 2019-01-18 a las 11 19 32" src="https://user-images.githubusercontent.com/3488092/51380883-0264cd80-1b13-11e9-959e-9204db991807.png">

Thank you

**Comment by MingweiSamuel** [comment]
(Fixed, this issue can be closed)
