### ISSUE TITLE
[BUG] API responses are damaged

### ISSUE THREAD

**Issue by yes973** [RiotGames/developer-relations#293]
**Problem Description**  

when I call positional-rectangles on Runeterra localhost client's API, some of responses(string) are damaged. so responsed object cause json parsing errors.

**Actual Result** 
**Expected Result**  

![error](https://user-images.githubusercontent.com/41465046/81647753-83627980-9468-11ea-9297-b42173e6f1b1.png)

Expected Results are bottom codelines in the screenshot.
I can escape the problem temporarily by attching string "r\":true}]}" , but still last value (LocalPlayer) is missing.

**Comment by Mimslade** [comment]
Yeah requests to the endpoint delivers malformed js missing a ending bracket.

**Comment by lucasMesquitaBorges** [comment]
Unfortunately DevRel can't take action in this issue. This is mentioned in the docs: https://developer.riotgames.com/docs/lol#league-client-api

> **NOTE:** We provide no guarantees of full documentation, service uptime, or change communication for unsupported services. This team does not own any components of the underlying services, and will not offer additional support related to them.

This issue is very old and I'm not sure if this error still occurs, but for similar issues that may occur in the League Client / Game Client, they aren't something DevRel can help on providing a solution.
