### ISSUE TITLE
[DOC] Account v1 getByRiotId required non-required parameter

### ISSUE THREAD

**Issue by simivar** [RiotGames/developer-relations#395]
**Bug Description**  
In the documentation of [getByRiotId endpoint](https://developer.riotgames.com/apis#account-v1/GET_getByRiotId) of Account v1 API `gameName` is described as **This field may be excluded**.

**Problem Description**  
When you scroll down to make a sample request `gameName` is required:
<img width="932" alt="image" src="https://user-images.githubusercontent.com/828020/97088236-cc317780-162f-11eb-9945-052f3553d8ad.png">

**Expected Result**  
Specify clearly in both places if the parameter is required or not.

**Actual Result**  
Misleading information

**Developer Impact**  
Misleading information can result in developers making wrong requests and using API not the way it was desired to be used.

**Comment by simivar** [comment]
Also, it would be nice to know what are the values expected in `tagLine` field as it looks like region name. If I had to guess I would say it's: EUNE, EUW, NA, but others...?

**Comment by thomasmarton** [comment]
tagLine can be anything, it's like the discriminator on discord, allows multiple people to have the same username
When Riot IDs were first announced, everyone got their region as their initial tagLine, but anyone can change that
https://support-leagueoflegends.riotgames.com/hc/en-us/articles/360041788533-Riot-ID-FAQ

**Comment by simivar** [comment]
@thomasmarton thank you. Still, it would be nice to unify the information about the requirement of the field.

**Comment by RiotTuxedo** [comment]
I'll update the documentation, but the confusion here is that you're mixing up the expectations for two fields that are named the same.

The path parameter `gameName` which is required to look up a player is always required. You can't look up a player with this method if you don't have their name.

The response body contains a field also called `gameName`. This response body is shared with this method but also the `getByPuuid` method. If you look up a player by their `gameName` and `tagLine` then these fields won't be excluded. However if you look up a player by their puuid, they may not have their `gameName` and `tagLine` set. As such, these fields may be excluded in that case.

The path params are required because that's how you're looking up the player, the fields in the response aren't guaranteed to be included if the player hasn't chosen an in-game name.

I'll update the documentation to better reflect this and close the ticket after.

**Comment by paaksing** [comment]
> This response body is shared with this method but also the getByPuuid method, and another method meant for RSO tokens (a /me method). If you look up a player by their gameName and tagLine then these fields won't be excluded. However if you look up a player with an RSO token, gameName and tagLine are only set if the player has chosen an in-game name. As such, these fields may be excluded in that case.

@RiotTuxedo Just to add up a bit, I sometimes do not see `gameName` and `tagLine` come back even if I use my prod key (not RSO), for example when I look up `RattlingBones#na1` it does not return me tagLine nor gameName.
```json
{
    "puuid": "o_S9AonsbzrL0axhffvStJXgmM3Z62kuxrwex7bR-9MiPznH_iHzqCzYS1Fy6eXj137CdLRwP9XySA"
}
```

**Comment by RiotTuxedo** [comment]
@paaksing Ah so what's happening here is that you're actually looking up your summoner and region as your gameName and tagLine and we're returning the account associated with it, but there is no account with the `RattlingBones#NA1` riot id. The riot id associated with this account is actually `RattlingBones#6774`. I'd prefer to leave this functionality because it allows for the lookup of summoner name region in place of the game name and tag line. But if we were being strict here, then we'd return a 404 since the riot id (game name and tag line) you looked up doesn't exist.

I've updated the documentation to better clarify that game name and tag line can be excluded from the response, but never from the query params.
