### ISSUE TITLE
[BUG] Riot API Issue

### ISSUE THREAD

**Issue by Leejung8763** [RiotGames/developer-relations#446]
**Issue Description**  
I tried to use options 'beginTime' and 'endTime' in Match-V4.
When I used only 'beginTime'=1612278000, It worked. 
But when I used both them 'beginTime'=1612278000 and 'endTime'=1612364400, It didn't work and get 400 error.
Is there something wrong..?

![image](https://user-images.githubusercontent.com/50440358/107001194-96726200-67cc-11eb-8e02-6aa9a644993f.png)

**Comment by bangingheads** [comment]
Per the documentation this is working as intended.

The begin time to use for filtering matchlist **specified as epoch milliseconds**. If beginTime is specified, but not endTime, then endTime defaults to the the current unix timestamp in milliseconds (the maximum time range limitation is not observed in this specific case). If endTime is specified, but not beginTime, then beginTime defaults to the start of the account's match history returning a 400 due to the maximum time range limitation. If both are specified, then endTime should be greater than beginTime. The maximum time range allowed is one week, otherwise a 400 error code is returned.

Your timestamps are not in the correct format so an error 400 is thrown.

**Comment by Leejung8763** [comment]
I'm really appreciate to your quick answer.
But, I still have some questions.

I used  'beginTime'=1612278000=2021.02.03 and 'endTime'=1612364400=2021.02.04.
So, I think all of conditions (1. maximum time range limitation, 2. endTime should be greater than beginTime) are satisfied.
If you don't mind, would you give me some examples for using these options?

ps. I'm not good at English. So if I'm rude or upset you, I'm really sorry...

**Comment by stelar7** [comment]
The max allowed time span is one week, not one month.

**Comment by Leejung8763** [comment]
> Per the documentation this is working as intended.
> 
> The begin time to use for filtering matchlist **specified as epoch milliseconds**. If beginTime is specified, but not endTime, then endTime defaults to the the current unix timestamp in milliseconds (the maximum time range limitation is not observed in this specific case). If endTime is specified, but not beginTime, then beginTime defaults to the start of the account's match history returning a 400 due to the maximum time range limitation. If both are specified, then endTime should be greater than beginTime. The maximum time range allowed is one week, otherwise a 400 error code is returned.
> 
> Your timestamps are not in the correct format so an error 400 is thrown.

I'm really appreciate to your quick answer.
But, I still have some questions.

I used 'beginTime'=1612278000=2021.02.03 and 'endTime'=1612364400=2021.02.04.
So, I think all of conditions (1. maximum time range limitation, 2. endTime should be greater than beginTime) are satisfied.
If you don't mind, would you give me some examples for using these options?

ps. I'm not good at English. So if I'm rude or upset you, I'm really sorry...
And I used 'Epoch & Unix Timestamp Conversion Tools' web site.
https://www.epochconverter.com/

**Comment by molenzwiebel** [comment]
Those timestamps are in seconds, not milliseconds. Multiply by 1000 (add three zeros) to get the correct values.

**Comment by Leejung8763** [comment]
> Those timestamps are in seconds, not milliseconds. Multiply by 1000 (add three zeros) to get the correct values.

You are right. Now it works.
I'm really appreciate it!!
