### ISSUE TITLE
[BUG] Valorant Desync

### ISSUE THREAD

**Issue by VALnoDesync** [RiotGames/developer-relations#508]
I am not an engineer or a tech savvy.
All I know is: Unfortunately there is "a lot" desync in the game and I can't say how or why.
In my humble opinion would be very helpful if you could implement a system to check if the client is in sync with the server.

I don't know why this matter has not been addressed earlier but is very disappointing.

Hope somebody with common sense could hear me out.

Thank you

**Comment by Token07** [comment]
Greetings,

Common sense would suggest starting at the README located on the page before you created this issue which states this issue tracker is not meant for game bugs.

> Verify that the issue you are about to report relates to the Riot Games Developer Ecosystem and is not a game bug (for game bugs please go here).

If you really want to report an alleged game bug, you need to start with player support.

**Comment by VALnoDesync** [comment]
Hello Token07,

I tried many times to solve the issue with them in vain, they want me to trace route (through ping plotter) 162.249.72.1 that clearly has an ICMP block and of course I get 100% PL.

Thank you for your answer anyway.

**Comment by Token07** [comment]
Unfortunately, there isn't really an escalation point beyond player support, they have to escalate it. I've dealt with them before too and it took 3 tickets there to get them to escalate, but then I never heard anything back afterwards, until reading the LoL patch notes to see that it was fixed.

**Comment by VALnoDesync** [comment]
I guess I hit a wall then. Unbelievable how much riot neglect players and issues.

Thank you for your time, much appreciated!

**Comment by catboy-oss** [comment]
They want you to traceroute it, not ping it. Only the last portion drops ICMP - it still tells you the path it takes all the way into riot's network handoff

**Comment by RiotTuxedo** [comment]
Hey @VALnoDesync I'm sorry that you feel neglected. The issue here is that it's not a viable option for us to sit down with millions of players to individually triage and debug issues on an individual basis. Instead, we often work to implement tooling to allow us to track issues with the client and game in aggregate. One of these methods is player support, which is equipped to handle common issues, but they also aggregate common ticket topics. This allows the game teams to understand what are common issues that players are writing in about.

I'd suggest continuing to research where your desync might be happening. There's potentially a large number of culprits here from your computer, your ISP, the Internet (and how your requests are routed), to our network, and our servers. If you like you might be able to team up with other players and work to isolate the issue. Once you've gotten as far as you can, you could submit a player support ticket with your findings and work to find other players who are experiencing the same issues and raise that issue as a group.

I hope this helps, but as @Token07 this forum isn't the place to address game bugs :(

**Comment by VALnoDesync** [comment]
> They want you to traceroute it, not ping it. Only the last portion drops ICMP - it still tells you the path it takes all the way into riot's network handoff

![162 249 72 1](https://user-images.githubusercontent.com/87811329/126679738-0d0ba368-bde7-4386-8151-3f65c68362a8.png)

I believe it's fine since I can play.
However looks like I use others IPs to play and they are fine.

![game](https://user-images.githubusercontent.com/87811329/126682106-134310fe-a95a-42b6-8efd-e0105f503e80.jpg)

**Comment by VALnoDesync** [comment]
> Hey @VALnoDesync I'm sorry that you feel neglected. The issue here is that it's not a viable option for us to sit down with millions of players to individually triage and debug issues on an individual basis. Instead, we often work to implement tooling to allow us to track issues with the client and game in aggregate. One of these methods is player support, which is equipped to handle common issues, but they also aggregate common ticket topics. This allows the game teams to understand what are common issues that players are writing in about.
> 
> I'd suggest continuing to research where your desync might be happening. There's potentially a large number of culprits here from your computer, your ISP, the Internet (and how your requests are routed), to our network, and our servers. If you like you might be able to team up with other players and work to isolate the issue. Once you've gotten as far as you can, you could submit a player support ticket with your findings and work to find other players who are experiencing the same issues and raise that issue as a group.
> 
> I hope this helps, but as @Token07 this forum isn't the place to address game bugs :(

I clearly understand what you mean.
I tried my best, I did put days and days to find out the cause of the issue but I don't feel that is something that I should do as a player. 
Unfortunately I also have limited skills/knowledge.

I want to gloss over why it wasn't recognized.
Thank you again, surely devs at riot listen to players.
