### ISSUE TITLE
[BUG] [Match v4 and v5] Missing PerkSubStyle

### ISSUE THREAD

**Issue by trebonius0** [RiotGames/developer-relations#534]
For this match: EUW1_5442606946, for participantId 8:
The "perkSubStyle" field is missing (in the match v4 object). 
In match v5, the style is "0" for substyle.

The two associated perks are 82xx, so this field value should be 8200.

Thanks

**Comment by RiotTuxedo** [comment]
Always finding the edge cases lol. I did some digging and basically, if a player's runes aren't set the style is set to 0 and the default runes are used which are configured based on each champion. This is basically a fallback mechanism to ensure a player always has runes.

It's unclear if the rune page isn't set because of a client error or a server error, but the result of the fallback mechanism is what you're seeing in match history. Since this is a potentially large investigation for a low impact issue, I don't foresee us digging into this further, but hopefully with this explanation you can code around this edge case. Closing for now. Feel free to reopen if you get more info.
