### ISSUE TITLE
[BUG] Match doesn't exist from Match V5 api

### ISSUE THREAD

**Issue by pitzcarraldo** [RiotGames/developer-relations#537]
**Bug Description**  
region: kr
matchId: 2978383790
- https://kr.api.riotgames.com/lol/match/v4/matches/2978383790 > exists
- https://asia.api.riotgames.com/lol/match/v5/matches/KR_2978383790 > 404

**Issue Comments**  
This is just one sample. There are more match ids that don't response a correct result.

**Comment by trebonius0** [comment]
This is actually expected @pitzcarraldo 
Match v5 only stores matches after some date (some day this year, I can't precisely remember when).
So it's "normal" that this match from a previous season is not stored in there.

**Comment by jonasdaniels** [comment]
another example
https://br1.api.riotgames.com/lol/match/v4/matches/2350453732 
https://americas.api.riotgames.com/lol/match/v5/matches/2350453732 
game created(utc): 7 September 2021 19:33:25.617

**Comment by pitzcarraldo** [comment]
@trebonius0 Thanks for the information.
I tried several cases, but condition is inconsistent. 

- Summoner A
    - Can get 600+ matches from `/lol/match/v5/matches/by-puuid` API.
        - https://asia.api.riotgames.com/lol/match/v5/matches/by-puuid/2Xw6tlk0hBI9L-aon4UDIK4UI9Es1rqCKR7PBFQsaWUvk4ElKVYCyBOwCFLlHjN0kqTT8_tmCxTa_Q/ids?start=500&count=100
    - Oldest Match Dec/11/2020
        - https://asia.api.riotgames.com/lol/match/v5/matches/KR_4841009776
- Summoner B
    - Can get 700+ matches from `/lol/match/v5/matches/by-puuid` API.
        - https://asia.api.riotgames.com/lol/match/v5/matches/by-puuid/RjBSbTz-kDhnef4oyOJN722u1P3xYzSR7bS48--jNr5VB978Gy0LzktitTqfouX3F4TuHk4__PizgA/ids?start=700&count=100
    - Oldest Match Dec/14/2020
        - https://asia.api.riotgames.com/lol/match/v5/matches/KR_4848097823
- Summoner C
    - Can get 700+ matches from `/lol/match/v5/matches/by-puuid` API.
        - https://asia.api.riotgames.com/lol/match/v5/matches/by-puuid/B8JluKt2wsiuTQQOPgpUfj7w8FCe-k8Mx_M2nocF1_DMaCu4rVgIB1lnJ_fnQZ86JTE7GyLyD8W39g/ids?start=700&count=100
    - Oldest Match May/14/2021
        - https://asia.api.riotgames.com/lol/match/v5/matches/KR_5193983541

**Comment by bangingheads** [comment]
@pitzcarraldo Your original match you posted in your issue is from October 9, 2017. Match-V5 was started at the very end of last season. For easier clarity we normally say the start of this season. It holds up to 1000 matches in the matchlist so it can differ how far back it goes based on the amount of games played.

For both Match-V4 and Match-V5 there's only a 2 year retention policy so technically this ID could disappear at any time from V4 as well.

PUUIDs are different across keys so I cannot verify who these summoners are, but likely they've played that amount of games that are showing in their matchlist since Match-V5 collection was started.

@jonasdaniels You have a wrong match id as it changes to BR1_matchId, your url would be https://americas.api.riotgames.com/lol/match/v5/matches/BR1_2350453732 which does currently exist.
