### ISSUE TITLE
Match v4 returns incorrect totalGames by default (when startIndex is less than 25)

### ISSUE THREAD

**Issue by timplaw** [RiotGames/developer-relations#55]
preconditions
1. Not sure
Steps to Reproduce
1. Search for summoner info about anyone in v4
2. use encrypted account id to search matchlist
Expected Result
1. totalGames value should be the total for that account by default and shouldn't depend on any parameters
Actual Result
![after changing startindex](https://user-images.githubusercontent.com/14845922/51080775-96680c80-16af-11e9-9107-384c35635db8.png)
![first startindex that works](https://user-images.githubusercontent.com/14845922/51080776-9700a300-16af-11e9-9ffe-1ea38700da96.png)
![last startindex that fails](https://user-images.githubusercontent.com/14845922/51080777-9700a300-16af-11e9-823e-1e5cc983c35d.png)

**Comment by RiotTuxedo** [comment]
Thanks for this report. We've been following this bug for a while. Here's what we know.

The inconsistency stems from a caching issue. There's a recent game cache that is being used when the query only returns the most recent 100-150 games (typically the first page). If your query returns matches not contained in the recent game cache, the API will properly return the `totalGames` that match your query.

Because this doesn't prevent the usage of the match API, and only makes it more difficult to work with it, the priority for resolving this bug is relatively low. We'll be looking for opportunities to fix this bug when there's work closely related to this bug has been prioritized.

**Comment by Demosthenexx** [comment]
Given this is a long standing low priority issue, can you update the API documentation implementation notes to document this behavior? There is a whole paragraph there for details about the parameters. Seems a sentence or two would suffice.

**Comment by tisbells** [comment]
Closing out old issues. Match-v4 is no longer supported, feel free to re-open or comment if you feel this is in error.
