### ISSUE TITLE
Valorant match api allow personal keys to access their own match stats

### ISSUE THREAD

**Issue by Tyrannicodin** [RiotGames/developer-relations#560]
Basically what is says in the title. I think you should allow personal api key users to access their own match stats without needing a production api key

**Comment by RiotTuxedo** [comment]
We require any VALORANT match history calls to first verify the player who owns their account is fine with making their match history public via RSO. We're not going to generate RSO clients for every personal key and we're not going to build a mechanism to  associate a key with an individual account (may times developers use a separate account than the one they play on), so unfortunately this request is unlikely to happen.

**Comment by jeffreyxchan** [comment]
I noticed that an app like valorant.op.gg does not require me to sign in in order to view my own match stats or the stats of other players. I'm assuming they're using a production key. Does a production key give you access to anyone's match history data regardless of whether they consent to it?

I'd like a personal API key to query my own valorant match stats without having to apply for a production key. So I'm trying to understand why this will not happen, or if there are other workarounds.

**Comment by geozukunft** [comment]
A production key gives you access to everyone's data but per [Riots policies](https://developer.riotgames.com/docs/valorant) you are not allowed to show personal data without the players consent first. 
From the policies: _If players have not opted into data sharing in their ecosystem, their information should not be made available to other players through their website, applications, or game overlays._

Without a players opt-in you are only allowed to show: 
_Do Not Require Player Opt-in
The following accepted use cases do not require a player to opt-in:

Aggregate player stats without any specific players.
Official ladder leaderboards._

But it's nothing new that the big sites break the policies. blitz.gg has been doing that for more than half a year too and Riot clearly does not care about the big sites. Talk about double standards.
