### ISSUE TITLE
Static Data page is missing from navigation

### ISSUE THREAD

**Issue by DrCyanide** [RiotGames/developer-relations#58]
https://developer.riotgames.com/static-data.html no longer shows up in the API Documentation drop down, despite being the only place to find out about ddragon information - including the JSON files, Images, and TAR files.

**Comment by MingweiSamuel** [comment]
It still contains a lot of useful information about ddragon. With a little bit of love (removing all static-data-api, and find-replace 6.24.1 -> 9.1.1) I think it's definitely worth having on the menu. Could also mention cdragon :)

Can also mention how unreliable the champion spell info is, since that comes up a lot.

**Comment by RiotTuxedo** [comment]
The static data documentation was removed because it was inaccurate. I'm labeling this as a feature request for data dragon.

**Comment by C4landra** [comment]
Totally Agree to this, took me some time to figure this out ^^ lucky i still had the link laying around somewhere, even tho its not accurate anymore, there is highly needed stuff for most applications.

**Comment by stelar7** [comment]
This page was added back a while ago, so this can be closed @RiotTuxedo (tho still outdated. )

**Comment by RiotTuxedo** [comment]
We've got a documentation rewrite planned as well. Gonna close this cause the original ticket talks about the menu item missing.
