### ISSUE TITLE
[Account] Can not connect to euw1 api - Destination Net Unreachable

### ISSUE THREAD

**Issue by Fabsi23** [RiotGames/developer-relations#584]
**Account Information**
What's your summoner name? 
FABSI on the developer portal and Fαbsi ingame.

Have you played any of Riot's games or did you just create an account for the Developer Portal?
I'm actively playing League of Legends

**Issue Description**  
Starting today I can no longer reach the euw api (euw1.api.riotgames.com) - other apis like na1 work fine. I tried pinging it and it always times out. Pinging it from my personal computer (not server) works. The application was running successfully for over 1.5 years and with no recent changes - also the API-key still works fine and normally. The IP of the server hasn't changed either.

Also the server can ping youtube, google and whatever without any problems

Below you can find the results of ping and traceroute that is run on the server.

I can't ping euw1.api.riotgames.com (104.160.144.188) because it fails at (61.43.235.210) - pinging 61.43.235.210 directly works without a problem. It appears that LG Dacom Corporation (owner of 61.43.235.210) no longer redirects to the API of league. Does that mean that RiotGames has to contact them in order to fix the problem or is there something I can do?

**What I've Tried**
What steps have you tried to resolve the issue.
- [ x ] Restarting the application and the server
- [ x ] Recompiling the application
- [ x ] Pinging the API directly without an application

**Repro Steps**
There is no exact reproduction since it only fails if run from that certain IP-Adress. Is it blacklisted? If so, why out of a sudden?

**Issue Context**

![image](https://user-images.githubusercontent.com/17888617/147513798-f57abf91-daf7-4c51-9518-f1800d2861b5.png)

**Comment by bangingheads** [comment]
61.43.235.210 is owned by LG DACOM Corporation and is part of your route to the server. This is before the edge of the Riot API.

Sounds like a routing issue on your host, not much Riot can do to help you here. I would contact your host / ISP of the host that you're having issues.

**Comment by FabsiGit** [comment]
Oh I did not know that. I will try contacting them. How did you know whether that IP was part of Riots API or not? Just so I can find this out if something similar happens in the future?

And thanks already!

**Comment by FabsiGit** [comment]
I talked to my hoster now and they said they can't change the route - they checked what the issue is and said that there's a problem with an upstream of riotgames at LG Dacom. I haven't found a way (like a contact formular) to contact LG Dacom Corporation.

The hoster suggested to contact riot games and ask for a different routing. Is that the best way or is there another possibility?

**Comment by RzR32** [comment]
Hey, has the error been found yet?
I have exactly the same problem and also only with the EUW1 API, others work fine.
I have tried something and maybe found something:
- on the left side of the picture you can see a console from one of my servers somewhere in Frankfurt, where something is running because of Riot API. As you can see this one has no successful connection.
- right the console is a connection setup from my local PC, which works fine.

As you can see at FIRST ping comes back a completely different IP and also at the tracert below you can see the difference ... is there somehow a hang together?

(I hope this is helpful)

![DEV-RiotGames](https://user-images.githubusercontent.com/46526880/152231835-087a268a-8da8-4673-a1d0-cd6102fea612.png)

**Comment by YaroslavMolchan** [comment]
Me too, but for ru region

**Comment by Fabsi23** [comment]
> Did you find any workaround to this? I'm currently experiencing the same problem

Since the problem still persists and it isn't possible to reach the server from my "main" location, I now rented a second (very weak) server in another country and I'm using it as a proxy that just forwards the request and returns the response

I would still prefer to have a reasonable routing that doesn't end in south korea though.

**Comment by Fabsi23** [comment]
I'm now able to reach the api normally again (without another server serving as a proxy) - so I'm closing this issue
