### ISSUE TITLE
[BUG] LOR SEA/APAC REQUESTS TAKING FOREVER

### ISSUE THREAD

**Issue by iann838** [RiotGames/developer-relations#614]
Requests to SEA/APAC are taking forever to respond since the last 2 days.

**Comment by MaouLegna** [comment]
To add a bit more information:
- Every since the APAC merge it was not uncommon to have a series of request that took a big amount of time (compared to EU/NA)  usually around 4x the time.

- From the 9th / 10th of March the issue exacerbated affecting pretty much all request. At least personally these days there was always around a 10% to 20% chance of getting a Bad Gateway (502 status) and overall around a 80% change of being able to have not NULL results.

- Most of these issues seems to have disappeared from about 4 hours from the writing of this message ( around 7:00 AM CET ) but the huge amount of time for a request still remain (around 7x the EU/NA time)

**Comment by tisbells** [comment]
Closing out old issues. We've had no recent reports this issue is still occurring. If you are still experiencing this, please comment or reopen.
