### ISSUE TITLE
[BUG] [LOR] inventory cards endpoint returns 503

### ISSUE THREAD

**Issue by niklod** [RiotGames/developer-relations#639]
**Bug Description**  
Endpoint `/lor/inventory/v1/cards/me` constantly returns 503 http code

**Problem Description**  
Endpoint `/lor/inventory/v1/cards/me` constantly returns 503 http code

**Expected Result**  
Endpoint `/lor/inventory/v1/cards/me` return a list of cards owned by the calling user

**Actual Result**  
Endpoint `/lor/inventory/v1/cards/me` returns 503 http code

**Developer Impact**  
Describe how this affects you as a developer. Please include the frequency and severity of the issue.

* Frequency: Every API call.
* Severity: When it happens, riot account syncing feature crashes.
* Cost: reputational losses. Community supporting expenses.
* User emails: I get frequent emails from users asking me about this issue.

**Player Impact**  
Describe how this affects League of Legends players. Please include the frequency and severity of the issue.

* Frequency: Every time the user try to sync account statistic, they experiennce this issue.
* Severity: When this bug happens, a user is unable to use account syncing feature.
* Quantity: There are ~1k players that experience this issue.
* Region: This affects players in Americas, Europe and APAC.

**Preconditions**  
What conditions must be met in order for this bug to occur?

1. Have refreshed token
2. Send request in Europe region for example:
```
curl --location --request GET 'https://europe.api.riotgames.com/lor/inventory/v1/cards/me' \
--header 'Authorization: Bearer {token}'
```

**Repro Steps**  
Step by step, what do you need to do to cause the bug? Note that GitHub will automagically number each step if you prefix the line with "1. "

1. Have refreshed token
2. Send request in Europe region for example:
```
curl --location --request GET 'https://europe.api.riotgames.com/lor/inventory/v1/cards/me' \
--header 'Authorization: Bearer {token}'
```

**Comment by niklod** [comment]
Issue still actual

**Comment by sethjwilliamson** [comment]
I also thought this was fixed for a while at the end of last week, but it turns out that there are still issues. With that said, I do think it's working better than last week.

If I recall, last week, any call to `/lor/inventory/v1/cards/me` or `/lor/deck/v1/decks/me` would always result in a 503 - Service Unavailable.

Since then, that has changed. Now, it seems that `lor/inventory/v1/cards/me` does work, but not the same as it used to. Maybe I'm misremembing, but I'm pretty sure the RSO endpoints should be able to be accessed from any "server" (americas, sea, europe). And it was recommended to just access the one that is closest to your server. Now, it is required to access the server of the player you are requesting info from. 
This means accessing the cards endpoint of cards for a player on the Americas server from  `https://americas.api.riotgames.com/lor/inventory/v1/cards/me` will return the cards correctly, but accessing the same player with `europe` or `sea` results in an empty array.

The `/lor/deck/v1/decks/me` still always results in 503 - Service Unavailable.

**Comment by tisbells** [comment]
Closing out old issues. We've had no recent reports this issue is still occurring. If you are still experiencing this, please comment or reopen.
