### ISSUE TITLE
[BUG] Match-V5: Some match IDs do not belong to the player

### ISSUE THREAD

**Issue by CurtisGreen** [RiotGames/developer-relations#714]
**Bug Description**  
Querying match history list sometimes gives matches that both do not adhere to request filters and worse do not belong to that player

**Expected Result**  
- Matches adhere to request filters
- Matches belong to the given player

**Actual Result**  
- Some matches work as expected
- Some are different queueIDs or are for completely different players (usually these coincide)

**Developer Impact**  
Developers have to do extra error handling and extra requests to handle the APIs sending back invalid data

* Frequency: Every API call to certain players
* Severity: When it happens the data is useless and you cannot render useful information to the player

**Player Impact**  
Matches that do not belong to the given player is very confusing

**Repro Steps**  
1. Look up the player `GamerGronk` on OCE
2. Use their puuid to get their match list: `https://sea.api.riotgames.com/lol/match/v5/matches/by-puuid/<puuid>/ids?queue=700&start=0&count=100&api_key=<key>`
3. Expect games with queueId 700 (clash), that GamerGronk has played in
4. Get this game: `OC1_532533756`: Which has a queueID of `1400` and does not contain GamerGronk's name or puuid
5. Get this game: `OC1_532526946`: Which has a queueID of `420` and does not contain GamerGronk

**Comment by iaace-NA** [comment]
I've heard about this issue second-hand

**Comment by RiotTuxedo** [comment]
OCE switched from the NA platform to the APSE platform. Hence why match history moved from `americas` to `sea`. As part of this move, there was a period of time where some match data was overridden. Looks like 223k matches between Monday, August 8th, 2022 @ 12AM GMT until Tuesday, August 23rd @ 7:13:16PM GMT. When a match gets overridden it'll still show up in the original players match history, but it won't have data from the original game.

As such, I'm going to close this since it is a known issue.
