### ISSUE TITLE
[Account]  I can't log in to the developer portal

### ISSUE THREAD

**Issue by dfd1123** [RiotGames/developer-relations#734]
**Account Information**
What's your summoner name (e.g., Tuxedo) or riot id (e.g., Tuxedo#AYAYA)?
Have you played any of Riot's games or did you just create an account for the Developer Portal?

**The summoner's name is 'Or갈파이터' and I've played League of Legends and signed up for the developer portal.**

**Issue Description**  
A clear and concise description of what the issue is.

**When I log in from the developer portal site, the zipper comes out as a function, but there is a problem, so I have to log out.**

**What I've Tried**
What steps have you tried to resolve the issue.

**All I can do is ask Riot.**

![스크린샷 2023-01-31 오후 2 00 17](https://user-images.githubusercontent.com/42544793/215669747-4165e39e-224b-4acb-a053-232240a58c0a.png)

**Comment by lucasMesquitaBorges** [comment]
Hey @dfd1123  I'm tackling old issues. Sorry for not answering this before.

Your account is not active. You will need to follow this [article](https://support-leagueoflegends.riotgames.com/hc/en-us/articles/360037644973-Recover-Your-Account) in order to recover your account.

Feel free to re-open this issue if needed.
