### ISSUE TITLE
[Account] 

### ISSUE THREAD

**Issue by ysh1537** [RiotGames/developer-relations#743]
Account Information
What's your summoner name (e.g., Tuxedo) or riot id (e.g., Tuxedo#AYAYA)?
Have you played any of Riot's games or did you just create an account for the Developer Portal?

riot id: jarvis0942

Issue Description
A clear and concise description of what the issue is.
You've logged in successfully, but your account is in a funky state so we need to take a look. Please contact us on [Twitter](https://twitter.com/RiotGamesDevRel), during office hours on [Discord](https://discord.gg/riotgamesdevrel), or create an [GitHub issue](https://github.com/RiotGames/developer-relations/issues/new?template=account_issue.md&title=%5BAccount%5D+).

What I've Tried
What steps have you tried to resolve the issue.

[v] Log out of the Developer Portal
[v] Attempt to log in via "Incognito Mode"
[v] Clear your browser cookies
[v] Attempt to login via a secondary device (mobile or different computer)
Repro Steps

Step 1
Step 2
Issue Context
Please add any additional context that is useful.

**Comment by lucasMesquitaBorges** [comment]
Hey @ysh1537 I'm tackling old issues. Sorry for not answering it before.

Your account is not active. You will need to follow this [article](https://support-leagueoflegends.riotgames.com/hc/en-us/articles/360037644973-Recover-Your-Account) in order to recover your account.

Feel free to re-open this issue if needed.
