### ISSUE TITLE
[BUG] LoL matches not found but returned by match history

### ISSUE THREAD

**Issue by Vidalee** [RiotGames/developer-relations#807]
**Bug Description**  

All LoL matches returned for the summoner "Spillerrrrrrrrrr" en EUW1 are currently deleted (probably too old ?)
These matches are 
```json
[
    "EUW1_5247329610",
    "EUW1_5247277526",
    "EUW1_5245272127",
    "EUW1_5244010798",
    "EUW1_5243888604",
    "EUW1_5243851397",
    "EUW1_5243116217",
    "EUW1_5242904237"
]
```
**Problem Description**  

It is expected that all games returned by [/lol/match/v5/matches/by-puuid/{puuid}/ids](https://developer.riotgames.com/apis#match-v5/GET_getMatchIdsByPUUID) are able to be queried using [/lol/match/v5/matches/{matchId}](https://developer.riotgames.com/apis#match-v5/GET_getMatch)

**Expected Result**  

The match data.

**Actual Result**  

```json
{
  "status": {
    "message": "Data not found - match file not found",
    "status_code": 404
  }
}
```
**Developer Impact**  

I did not handle the case where the API would return a 404 for [/lol/match/v5/matches/{matchId}](https://developer.riotgames.com/apis#match-v5/GET_getMatch) thus the pipeline for this user crashed when they tried to log in on my website.

**Repro Steps**

- Get the puuid for summoner "Spillerrrrrrrrrr" en EUW1 using [/lol/summoner/v4/summoners/by-name/{summonerName}](https://developer.riotgames.com/apis#summoner-v4/GET_getBySummonerName)
- Get their match history using this puuid on europe using [/lol/match/v5/matches/by-puuid/{puuid}/ids](https://developer.riotgames.com/apis#match-v5/GET_getMatchIdsByPUUID)
- Find a match ID that matches the list posted earlier and use [/lol/match/v5/matches/{matchId}](https://developer.riotgames.com/apis#match-v5/GET_getMatch) to see the 404 error.

**Comment by dcapape** [comment]
Last time it took a week... let's see this time

**Comment by geozukunft** [comment]
It seems like these are games that are already expired and older than 2 years my guess would be sometime between December 2020 - March 2021

**Comment by dcapape** [comment]
Matches from yesterday are the same. 
Game ID: EUW1_6563624139
Game Mode: CLASSIC
Game played at: 23/08/2023 02:51
{
    "status": {
        "message": "Data not found - match file not found",
        "status_code": 404
    }
}

Featured Games is nor working also:
{
    "status": {
        "message": "Service unavailable",
        "status_code": 503
    }
}

**Comment by geozukunft** [comment]
I am actually seeing increasing amounts of 404s for matches for a timeframe between Nov 22 to now as well.
Following regions have higher amounts (theoretically there should be no game that 404s considering these are matchids that are less than 1 year old) 
KR: 55500
TW2: 13500
VN2: 5000
JP1: 2000
OC1: 1900

All other platforms have numbers lower than 1000 404s.
Are this custom games / practice tool matchids that are being "leaked" out again or is there some other issue going on? 
The matchids were all requested for a max time back to Nov 22 (except for the ex-garena platforms those are since the start of the API in January)

If needed I can send over all the matchids that 404ed

**Comment by geozukunft** [comment]
I rechecked the numbers on some platforms, timeframe is still games between Nov 2022 and now 
KR: >110k
EUW: >120k
TW2: >17k
VN2: >16k
JP1: >5k
OC1: >3,5k

**Comment by dcapape** [comment]
How did you get these MatchIDs?
Did you see if the dates of the matches are in groups of some days?
Sometimes you can see in the client that the match history from a game has been lost, but it doesn’t happen too often.

**Comment by geozukunft** [comment]
By downloading every single players matches. I can give rough timeframes for when those games likely happened based on the matchIds but considering those games 404ed I obv cannot say when they were played and which queue they were in as there is no data to go off from.

**Comment by dcapape** [comment]
Well, we can try to play some Practice Tool, custom and Tutorial games and later just check if we are getting ids from these games and to see if the timeframe of the games are giving us 404.
I can guess that timeframe for practice tools will give 404 since you can forward the timer and the match is probably running locally.

**Comment by Jeothesmar** [comment]
I am currently getting the same error too :(
Example match: NA1_4786826019

**Comment by geozukunft** [comment]
Any news on this topic @tisbells ?

**Comment by tisbells** [comment]
Hi there - So we've heard back and there is no singular root cause for this. There's an estimated fraction of a % of missing matches  from the API caused by a variety of things such as network or service errors. Unfortunately there is no fix for retrieving the missing matches, but the team is actively working on adding measures in the services to reduce the chance of missing match data.

**Comment by Ismaaa** [comment]
Hi!
Is there any update one this?

**Comment by Querijn** [comment]
This issue is closed as "won't fix". This generally means there won't be an update on it.
