### ISSUE TITLE
Tournament v4 Callback - Summoner ID missing

### ISSUE THREAD

**Issue by bashgeek** [RiotGames/developer-relations#85]
Hi there,
since the switch to the tournament API in v4, the callback after the match is not containing any Summoner ID's anymore, which is not documented properly (https://developer.riotgames.com/tournament-api.html).

Is there any chance we can get the Summoner IDs (encrypted, of course) back in there anytime soon? Since we need the IDs to cross-check our database we'll have to manually call the match API again for the details, which can certainly be avoided, especially because there seem to be some race-conditions in play, sometimes the match is not available via the API yet, when the callback is sent out, sometimes not even after a few seconds, which really screws with our realtime system at this point :-)

Thanks!

**Comment by RiotTuxedo** [comment]
The issue here is that the tournament service makes a callback directly to the tournament provider. The encrypted ids are managed by the API and without consulting the API there isn't a great way for the tournament service to provide these encrypted ids.

There is a meta data field that can be set by the tournament provider. At this point, the best solution would be to add information into this meta data field to correlate those summoner names with the appropriate player id. I'm not sure about the exact length that the meta data field will allow, so I'd suggest including some reference so you can look up these associations. Perhaps an id that correlates to a map of summoner names to encrypted ids?

The summoner names aren't likely to change during the duration of a match, and if you restrict the list of summoners allowed to join a lobby right before the match begins the list would only be invalid if the player changed their name right before the match starts. If there is an inconsistency, you should be able to look up the summoner name and sort out inconsistencies.

Obviously not ideal, but the priority on including encrypted player ids would likely be low and the effort to accomplish it fairly significant.
