### ISSUE TITLE
On the reference page select which app to execute a method with

### ISSUE THREAD

**Issue by stelar7** [RiotGames/developer-relations#90]
As its now, only the devkey can be used to make calls on the devportal. It would be nice if this could default to an active personal key if you had one, or just be selectable.

**Comment by RiotTuxedo** [comment]
There's a body of work we're scoping out that includes work on documentation and the reference page. I want to include this feature as part of that work.

**Comment by MingweiSamuel** [comment]
Here are my personal thoughts:

1. Being able to just click and go on the methods without entering long encrypted ids is nice. Personally I don't care too much if it defaults to my own account or an account I can manually specify.

2. I'm not sure how to tell right now what methods I have access to. (I like being able to see everything in the portal and have any disabled methods be grayed out or otherwise indicated. And would be nice to have a list on the app page.)

3. This is the most useful new feature for me because of the encryption. My current workflow is to open the reference, run a method, click the url to open it in a new tab, then copy paste in my other app's api key to get the response I need.

I'm indifferent to issue/3, I don't use the graph often and usually just check for any 429 response codes.

**Comment by RiotTuxedo** [comment]
Fair to say you only really care about #3 then? With the new encryption it actually can just make the reference page almost useless if it defaults to the wrong app. #1 is nice, but you can work around it, so not that big of a deal. #2 is just useful information.

**Comment by stelar7** [comment]
1. is not really needed imo, using yourself as the default is good enough in 99% of cases. Its a nice feature, but low-pri.

2. see @MingweiSamuel's answer to this one

3. This is also a nice feature, but more than selecting an app, having it default to an always-active key would be prefered.

**Comment by RiotTuxedo** [comment]
I'm assuming the same always active key? We'll just remember whichever one you selected last.

**Comment by stelar7** [comment]
fixed today? @RiotTuxedo
