### ISSUE TITLE
Correct summoner name

### ISSUE THREAD

**Issue by Andreqko** [RiotGames/developer-relations#93]
Hi! I have an issue with api summoner name.
When im trying to get summoner profile through nickname (for example ÉxıłeÐ) am always getting an error "Request path contains unescaped characters". IDK how to replace this special characters. When im typing normal nickname with common characters all is fine. Somehow opgg is doing well with this issue. 
Help me pls. Ty.

**Comment by Querijn** [comment]
Hey there!

This section is mostly with bugs and issues that you have encountered. Your post here does not contain either of these, so I suggest in the future you hop on to the [discord](https://discord.gg/riotapi).

You need to escape your characters. The function name for these depend on your language of choice:
Javascript has [encodeURI](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) or [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) for instance.
PHP has [urlencode](http://php.net/manual/en/function.urlencode.php)

You can probably find the one for your language of choice with searching any of the terms mentioned above.

OP.GG does it well because:
1. They escape their characters if you search for it on the website
2. Chrome and other common modern browsers escape characters when you enter them into the address bar.

**Comment by Andreqko** [comment]
Thx :)

**Comment by Andreqko** [comment]
Delete this issue pls!

**Comment by Querijn** [comment]
Press close
