### ISSUE TITLE
Constant 400s when trying to query Summoner Info

### ISSUE THREAD

**Issue by bradvandyk** [RiotGames/developer-relations#953]
**Account Information**
What's your summoner name (e.g., Tuxedo) or riot id (e.g., Tuxedo#AYAYA)?
Narkazokh

Have you played any of Riot's games or did you just create an account for the Developer Portal?
Yes. Both player and developer

**Issue Description**  
Always getting 400s invalid IDs when querying https://na1.api.riotgames.com/lol/summoner/v4/summoners/me

Have tried resetting developer API key twice.

**What I've Tried**
Query param, body param, via python, via web request in Riot Developer API. I'm able to get successful responses for champion rotation and other simple requests but not getting Summoner info

- [x] Log out of the Developer Portal
- [x] Attempt to log in via "Incognito Mode"
- [x] Clear your browser cookies
- [ ] Attempt to login via a secondary device (mobile or different computer)

**Repro Steps**

1. Go to https://developer.riotgames.com/apis#summoner-v4/GET_getByAccessToken
2. Execute with query or body param
3. Response is
    "status": {
        "message": "Bad Request - invalid token",
        "status_code": 400
    }
}

**Issue Context**
Please add any additional context that is useful.

**Comment by Cypherous** [comment]
Thats an RSO endpoint, which only production keys have access to, your developer key won't have access, can you confirm you have a production key with RSO access?

**Comment by Cypherous** [comment]
Yeah i would ignore that as that is likely wrong

If you visit the endpoint https://developer.riotgames.com/apis#account-v1/GET_getByAccessToken and scroll down you'll likely see 

![image](https://github.com/RiotGames/developer-relations/assets/4437781/e60ac89e-09c6-4138-ac47-bdbae2c1323f)

**Comment by bradvandyk** [comment]
Correct. I see that for `https://developer.riotgames.com/apis#account-v1` but not for `https://developer.riotgames.com/apis#summoner-v4`.

In order to create a production key, it looks like I need to have a full prototype and app/website already running. I'm using this for a small personal project (which eventually I'd like to publish to the iOS App Store).

Is it not possible to use the developer key to test this out so I can build the prototype? Or do I need to submit an application for a production key now?

**Comment by Cypherous** [comment]
You would need a production key to get access to RSO, although you probably don't actually need RSO unless you're trying to link a user account to a specific league account, the name and tagline is enough to do a lookup

Also worth noting that there are extra requirements if you want to release an iOS app as you'll specifically need to tell them in the application that you're releasing an app as there is documentation that riot will need to provide you in order to upload it and not have the app flagged automatically

And yes for all production keys a website detailing what your product does is a requirement and the app store page would not be enough for that

**Comment by bradvandyk** [comment]
That's fine I can create a website but I can't create an app or a prototype without using the developer key. Just seems backwards to use a production key for development purposes.

I don't need RSO at least I don't think right now. I'm just trying to create an app that shows my current summoner match history using SwiftUI. Happy to create a website for that if required in advance.

**Comment by Cypherous** [comment]
Yeah you can just skip the RSO part and just use the name + tagline endpoint on account-v1 to get the PUUID and then do your searches from there, when it comes to apps i'm not sure if they need to see an actual prototype, if you have a website that details what you're making, how it will work and some screenshots of a development build of the app you should be good to go

Not familiar with how development works with iOS as with android you can just self sign and sideload a development build of an app on to a device in order to test it, i assume iOS has some sort of equivalent, or atleast some sort of development studio that can run the app in an emulator of sorts for you to take some images of etc

**Comment by bradvandyk** [comment]
Cool, that worked with name+tagline. I was then able to use the puuid to get match info. This gives me a good starting point. Thanks @Cypherous !

**Comment by tisbells** [comment]
Closing as this seems resolved. Feel free to reply or open a new issue if needed.

**Comment by markjanzer** [comment]
@tisbells I don't think this is resolved. It looks like the primary issue is that the Summoner V-4 is shown to be accessible by development key in the `https://developer.riotgames.com/app/:id/apis` url. To resolve this the API path should either be removed from this list or have its permissions changed to allow for use with development api keys. 

This issue could be re-opened, or if you want me to open another ticket I'd be happy to do that. Or if it's out of scope for some for some strange technical we can just let it go to, I'm fine either way.

**Comment by bangingheads** [comment]
@markjanzer RSO endpoints like the /me need a RSO token which is impossible to get without a production application and RSO access. They don't actually take an API key so they are a little different.

If you'd like to troubleshoot any issues you're having come to the [Third Party Developer Discord](https://discord.gg/riotgamesdevrel) and we can help troubleshoot your issues there instead of commenting on a closed ticket.
