### ISSUE TITLE
[BUG] Potential RSO service outage/instability

### ISSUE THREAD

**Issue by whyando** [RiotGames/developer-relations#954]
**Bug Description**  
When our users sign in with RSO, when our app calls the /token endpoint, it hits this error:
```
{
  error: 'invalid_client',
  error_description: 'Invalid client: Possible causes may be 1) missing / invalid client_id; 2) missing client authentication; 3) invalid or expired client secret; 4) invalid or expired JWT authentication; 5) invalid or expired client X.509 certificate; 6) an unexpected client authentication method'
}
```

I believe this is a bug or service outage because it was working before and our code making this request hasn't changed, and the client_assertion is not close to expiring. (Although it is now over 1 year since it was issued).

**Comment by DarkIntaqt** [comment]
Hi, I suppose everything worked and this appeared just recently, right? Have you checked the possible causes? Maybe they deprecated a method or the secret actually changed (even tho I have never heard of that). 
I totally believe that this is a serious bug report, however there is a slight chance that this can get resolved otherwise :)

**Comment by whyando** [comment]
> Hi, I suppose everything worked and this appeared just recently, right?
yes, exactly

> Have you checked the possible causes? Maybe they deprecated a method or the secret actually changed (even tho I have never heard of that).
I've referenced https://docs.google.com/document/d/e/2PACX-1vTSthxkWOIqPFe8Xqqjv4Ona5pRa5W3X6bLg4I47X15gJjG9ae-HU5a0by7VIVLWdPMgB9fTr5gvQcY/pub to check that the 'private key JWT' method is still supported yes. (Although I understand the preferred method is now client secret basic).

**Comment by serkanbal** [comment]
I know that DevRel communicated that this issue is resolved in a tweet; however we get reports that users are still having issues with RSO (very rarely).
Users say that the first time they try to sign in, they see the error page I've shared. When I ask them to try again, they mostly (though not always) are able to sign in without any issue; but this seems like a pattern. I don't have any idea on how long they wait between the 1st and 2nd login attempts.
Here is the Riot ID of such a player:
- Elrond87#5063
Hope that this helps.
![IMG_5936](https://github.com/user-attachments/assets/03e77bcf-2277-4684-9a0d-d23e256f7e35)

**Comment by whyando** [comment]
This issue is now resolved for us.
